# Generated by Django 5.0.6 on 2024-05-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isAvailable', models.BooleanField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('imageUrl', models.CharField(max_length=255)),
            ],
        ),
    ]
